version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      time: "06:00"
      timezone: Europe/London
    groups:
      routine-updates:
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /functions
    schedule:
      interval: monthly
      time: "06:15"
      timezone: Europe/London
    groups:
      routine-updates:
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /email-worker
    schedule:
      interval: monthly
      time: "06:30"
      timezone: Europe/London
    groups:
      routine-updates:
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: "06:45"
      timezone: Europe/London
    groups:
      routine-updates:
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5
